### ISSUE TITLE
Please publish Debian packaging

### ISSUE THREAD

**Issue by intrigeri** [subgraph/subgraph-oz-profiles#1]
Hi!

I've been able to build a Debian package of oz, thanks to the recent packaging improvements you've published there. Cool! But the resulting package can't be installed properly, as it depends on the oz-profile package, and I could not find out how one is supposed to build that one. (Meanwhile, you might want to make that hard dependency a Recommends?)

So it would super nice to publish your Debian packaging for oz-profiles. Thanks in advance!

Cheers!

**Comment by xSmurf** [comment]
It's already published in the debian/ branch. More so this is a repository containing curated profiles for SGOS, there's no intention to maintain it "for debian".

**Comment by intrigeri** [comment]
> It's already published in the debian/ branch.

Thanks! (How come I could miss that one, but not the other ones, I dunno.)

> More so this is a repository containing curated profiles for SGOS, there's no intention to maintain it "for debian".

OK.
